import { StyleSheet } from "react-native";

export const ui = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F6F7FB" },
  container: { width: "100%", maxWidth: 980, alignSelf: "center", gap: 12, paddingTop:10},
  adminHome: { flex: 1, width: "100%", maxWidth: 980, alignSelf: "center" },
  adminHomeHeader: { gap: 12, paddingTop: 10 },
  patientListScroll: { flex: 1 },
  patientListScrollContent: { gap: 12, paddingBottom: 28 },
  patientListCard: { marginTop: 0 },
  patientCardEmail: { fontSize: 15, color: "#667085", textAlign: "center", paddingBottom:4 },
  loginBlock: { marginVertical: 50 },
  card: { backgroundColor: "white", borderRadius: 12, padding: 14, borderWidth: 1, borderColor: "#E7E8EF", gap: 8, marginTop:10 },
  heading: { fontSize: 24, fontWeight: "700", color: "#101827" },
  headingCentered: { textAlign: "center" },
  adminDashboardHeading: {
    fontSize: 24,
    fontWeight: "700",
    color: "#101827",
    textAlign: "center",
    paddingTop: 16,
  },
  patientRecordIdHeading: {
    fontSize: 24,
    fontWeight: "700",
    color: "#101827",
    textAlign: "center",
    paddingTop: 16,
  },
  welcomeText: { color: "#667085", fontSize: 17, textAlign: "center" },
  elevatedCard: {
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 6,
  },
  subheading: { fontSize: 18, fontWeight: "600", color: "#111827" },
  patientListTitle: { fontSize: 20, fontWeight: "600", color: "#101827", textAlign: "center", paddingBottom:15 },
  label: { fontSize: 13, color: "#334155", fontWeight: "600" },
  input: {
    borderWidth: 1,
    borderColor: "#CFD4E1",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "white",
  },
  button: {
    backgroundColor: "#2155F5",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginVertical:10
  },
  buttonPatientRecordNav: {
    backgroundColor: "#2155F5",
    paddingHorizontal: 14,
    paddingVertical:12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  buttonCreatePatient: {
    backgroundColor: "#2155F5",
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
    alignSelf: "center",
    width: "88%",
    maxWidth: 340,
  },
  buttonAddAppointment: {
    backgroundColor: "#2155F5",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
    alignSelf: "center",
    width: "82%",
    maxWidth: 320,
  },
  buttonSecondary: {
    backgroundColor: "#C2D2FF",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  visitAdminButton: {
    backgroundColor: "#C2D2FF",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    width: "90%",
    maxWidth: 320,
  },
  buttonDanger: {
    backgroundColor: "#FAE4E4",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: { color: "white", fontWeight: "700" },
  secondaryText: { color: "#1740C8", fontWeight: "700" },
  secondaryTextLarge: { fontSize: 16 },
  dangerText: { color: "#BE123C", fontWeight: "700" },
  logoutText: { fontSize: 18 },
  logoutButton: { paddingHorizontal: 50, paddingVertical: 12, alignSelf: "center", marginTop:10 },
  muted: { color: "#667085", fontSize: 13 },
  emptyStateText: { color: "#667085", fontSize: 15, textAlign: "center" },
  tabRow: { flexDirection: "row", marginTop: 4, borderBottomWidth: 1, borderBottomColor: "#E7E8EF" },
  tabButton: { flex: 1, alignItems: "center", paddingVertical: 10, borderBottomWidth: 2, borderBottomColor: "transparent" },
  tabButtonActive: { borderBottomColor: "#2155F5" },
  tabButtonInactive: { borderBottomColor: "transparent" },
  tabLabelActive: { color: "#2155F5", fontWeight: "700", fontSize: 16 },
  tabLabelInactive: { color: "#667085", fontWeight: "600", fontSize: 16 },
  appointmentRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 10 },
  appointmentProviderText: { color: "#111827", fontWeight: "600", flex: 1, fontSize:16, marginLeft:10 },
  appointmentDateText: { color: "#111827", fontSize: 16, textAlign: "right", marginRight: 10},
  dosageIndented: { paddingLeft: 10 },
  medicationTitleText: { fontSize: 20, fontWeight: "700", color: "#111827" },
  medicationDetailText: { fontSize: 16, color: "#111827" },
  rowDivider: { borderBottomWidth: 1, borderBottomColor: "#E7E8EF" },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  rowCentered: { flexDirection: "row", justifyContent: "center" },
  rowWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  providerCardRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  providerCardContent: { flex: 1, gap: 4 },
  providerCardActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  iconImage: { width: 16, height: 16, resizeMode: "contain" },
  modalBackdrop: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
  },
  modalCard: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    gap: 12,
    borderWidth: 1,
    borderColor: "#E7E8EF",
    overflow: "visible",
  },
  modalFooterRow: { flexDirection: "row", gap: 10, marginTop: 4 },
  modalButtonFlex: { flex: 1, marginVertical: 0 },
  selectFieldWrap: { position: "relative", zIndex: 20, marginBottom: 4 },
  selectControl: {
    borderWidth: 1,
    borderColor: "#CFD4E1",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selectControlText: { color: "#111827", fontSize: 15, fontWeight: "600" },
  selectOptionsWrap: {
    position: "absolute",
    top: 48,
    left: 0,
    right: 0,
    borderWidth: 1,
    borderColor: "#E7E8EF",
    borderRadius: 10,
    backgroundColor: "white",
    zIndex: 30,
    elevation: 8,
  },
  selectOption: { paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#E7E8EF" },
  selectOptionActive: { backgroundColor: "#F5F8FF" },
});
